project_name: github-releases-notifier
release:
  github:
    owner: justwatchcom
    name: github-releases-notifier
  name_template: '{{ .Tag }}'
builds:
- goos:
  - linux
  - darwin
  goarch:
    - amd64
    - arm
    - arm64
  goarm:
    - "6"
  main: .
  binary: github-releases-notifier
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -extldflags '-static'

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
dist: dist
changelog:
  filters:
    exclude:
      - typo
      - Fix
      - Merge
      - WIP
archive:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format: tar.gz
  files:
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
dockers:
- image: justwatchcom/github-releases-notifier
  goos: linux
  goarch: amd64
  goarm: ''
  binary: github-releases-notifier
  dockerfile: Dockerfile.amd64
- image: justwatchcom/github-releases-notifier-armv6
  goos: linux
  goarch: arm
  goarm: '6'
  binary: github-releases-notifier
  dockerfile: Dockerfile.armv6
- image: justwatchcom/github-releases-notifier-arm64
  goos: linux
  goarch: arm64
  binary: github-releases-notifier
  dockerfile: Dockerfile.arm64
env_files:
  github_token: ~/.goreleaser.token
