language: go

go:
  - 1.10.x

services:
  - docker

before_install:
  - go get -v github.com/golang/lint/golint
  - curl -sL http://git.io/goreleaser | bash -s -- -v
  - mv "${TMPDIR}/goreleaser" /go/bin/

script:
  - make clean
  - make vet
  - make lint
  - make test
  - make build
