language: go

go:
  - 1.10.x

before_install:
  - go get -v github.com/golang/lint/golint
  - curl -sL http://git.io/goreleaser | bash

script:
  - make clean
  - make vet
  - make lint
  - make test
  - make build
