FROM golang:1.9 as builder

ADD . /go/src/github.com/justwatchcom/github-releases-notifier
WORKDIR /go/src/github.com/justwatchcom/github-releases-notifier

RUN make buildarm

FROM arm32v6/alpine:3.7
RUN apk --no-cache add ca-certificates

COPY --from=builder \
  /go/src/github.com/justwatchcom/github-releases-notifier/github-releases-notifier \
  /bin/github-releases-notifier

ENTRYPOINT [ "/bin/github-releases-notifier" ]
